# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  ...
}:
{
  imports = [ ];

  boot = {
    extraModulePackages = with config.boot.kernelPackages; [
      it87
      zenpower
    ];

    initrd = {
      availableKernelModules = [
        "ahci"
        "nvme"
        "sd_mod"
        "usb_storage"
        "usbhid"
        "xhci_pci"
      ];

      kernelModules = [ "dm_thin_pool" ];

      supportedFilesystems = [ "zfs" ];
    };

    kernelModules = [
      "kvm-amd"
      "it87"
      "vfio"
      "vfio_iommu_type1"
      "vfio_pci"
      "vfio_virqfd"
    ];

    # kernelPackages = pkgs.linuxPackages_latest;
    loader = {
      grub.devices = [
        "/dev/sda"
        "/dev/sdb"
        "/dev/sdc"
      ];

      efi.canTouchEfiVariables = true;

      systemd-boot = {
        enable = true; # Use the systemd-boot EFI boot loader.
        consoleMode = "max";
      };
    };

    supportedFilesystems = [
      "xfs"
      "zfs"
    ];
  };

  environment.systemPackages = with pkgs; [
    hddtemp
    lm_sensors
    thin-provisioning-tools
  ];

  fileSystems = {
    "/" = {
      device = "rpool/safe/root/nixos";
      fsType = "zfs";
    };

    "/boot" = {
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };

    "/home" = {
      device = "rpool/safe/home";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

    "/home/rcorrear/Documents" = {
      device = "files.home.arpa:/rcorrear/Documents";
      fsType = "nfs4";
      options = [
        "sec=sys"
        "x-systemd.automount"
        "x-systemd.idle-timeout=600"
        "noauto"
      ];
    };

    "/home/rcorrear/Games" = {
      device = "/dev/mapper/data-games";
      fsType = "xfs";
    };

    "/home/rcorrear/Projects" = {
      device = "files.home.arpa:/rcorrear/Projects";
      fsType = "nfs4";
      options = [
        "sec=sys"
        "x-systemd.automount"
        "x-systemd.idle-timeout=600"
        "noauto"
      ];
    };

    "/nix/store" = {
      device = "/nix/store";

      options = [ "bind" ];
    };
  };

  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    keyboard.uhk.enable = true;

    nvidia = {
      modesetting.enable = true;
      open = false;
      powerManagement.enable = true;
    };

    graphics = {
      enable = true;
      enable32Bit = true;
    };

    sane = {
      enable = true;
      extraBackends = [ pkgs.hplipWithPlugin ];
      openFirewall = true;
    };

    sensor = {
      hddtemp = {
        enable = true;
        drives = [ "/dev/disk/by-path/*" ];
      };
    };
  };

  pciPassthrough = {
    cpuType = "amd";
    kvmfr = true;
    libvirtUsers = [ "rcorrear" ];
    pciIDs = "10de:2206,10de:1aef";
  };

  swapDevices = [ ];
}
