"on":
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  flake-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Nix flake check ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      # yamllint disable-line rule:line-length
      - uses: wimpysworld/nothing-but-nix@687c797a730352432950c707ab493fcc951818d7
        if: matrix.os == 'ubuntu-latest'
      # yamllint disable-line rule:line-length
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25
      # yamllint disable-line rule:line-length
      - uses: DeterminateSystems/magic-nix-cache-action@1828eb4e5414b8dfe36daae53ea3e4b8c3fdec7a
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - run: nix flake metadata
      - run: |
          cat <<-EOF > modules/ci-runtime.nix
          # CI-specific NixOS module - skip expensive operations
          { lib, ... }:
          {
            documentation.man.generateCaches = lib.mkForce false;
            documentation.nixos.enable = lib.mkForce false;
          }
          EOF
      - run: nix flake check
