---
"on":
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  flake-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Nix flake check ${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      # yamllint disable-line rule:line-length
      - uses: wimpysworld/nothing-but-nix@dd6ef566962bfa4656301706035da97ebbe90e9b
        if: matrix.os == 'ubuntu-latest'
      # yamllint disable-line rule:line-length
      - uses: DeterminateSystems/nix-installer-action@a4f499a84c7bd15903c67fa79a1d98dd9b6d8c84
      # yamllint disable-line rule:line-length
      - uses: DeterminateSystems/magic-nix-cache-action@20eea2e172f7f7487136e7a1a2f5b37aeb0e67bd
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - run: nix flake metadata
      - run: |
          cat <<-EOF > modules/ci-runtime.nix
          # CI-specific NixOS module - skip expensive operations
          { lib, ... }:
          {
            documentation.man.generateCaches = lib.mkForce false;
            documentation.nixos.enable = lib.mkForce false;
          }
          EOF
      - run: nix flake check
